import {defineStore} from 'pinia'

export const useSettingsStore = defineStore('useSettingsStore', {
  state: () => ({
    "passwordProtection": "0",
    "phrase": "",
    "passwordHint": "",
    "videoPreviewEnabled": "0",
    "videoPreviewStatic": "thumb",
    "videoPreviewHover": "video",
    "delayVideoPreview": "0",
    "appColorLightHeader": "#9298EB",
    "appColorLightPrimary": "#8A86F2",
    "appColorLightSecondary": "#F8B31A",
    "appColorDarkHeader": "#6E6AAD",
    "appColorDarkPrimary": "#887ED5",
    "appColorDarkSecondary": "#E98700",
    "headerGradientLight": "linear-gradient(to right,#ffb458,#6868eb)",
    "headerGradientDark": "linear-gradient(to right,#a9743d,#4a3c81)",
    "darkMode": "0",
    "headerGradient": "0",
    "colorScroll": "0",
    "textFont": "Roboto",
    "headerFont": "Roboto",
    "bottomBar": "0",
    "showPlaylistsInNavigation": "1",
    "showMarkersInNavigation": "1",
    "numberOfPagesLimit": "7",
    "gapSize": "2",
    "isPlayVideoInSystemPlayer": "0",
    "typingFiltersDefault": "0",
    "watchFolders": "0",
    "selectedDisk": "",
    "zoom": "1",
    "checkForUpdatesAtStartup": "1",
    "showIconsOfMetaInEditingDialog": "1",
    "showEmptyMetaValueInCard": "1",
    "showIconsInsteadTextOnFiltersChips": "0",
    "showHeaderImageAboveProfile": "1",
    "showExperimentalFeatures": "0",
    "showSavedFilters": "1",
    "showAdultContent": "1",
    "registration": "",
    "databaseVersion": "",
    "restorePlaybackTime": "1",
    "locale": "en",
    "ratingAndFavoriteInCard": "1",
    "group_chips_in_card_description": "1",
    "show_preset_metadata_in_card": "1",
    "count_number_of_views": "1",
    "meta_sort_mode": "menu",
    "system_dark_mode": "1",
    "open_player_in_separate_window": "1",
    "show_quick_action_button": "1",
    "play_sound_on_video_preview": "1",
    "big_video_preview": "1",
    "big_video_preview_delay": "2000",
    "show_salutation": "1",
    "show_ip_at_home_screen": "1",
    "home_widgets_config": "",
    "show_alert_new_tool_words": "1",
    "show_default_meta_outlined": "1",
    "show_default_meta_label": "1",
    "show_default_meta_filesize": "1",
    "show_default_meta_duration": "0",
    "show_default_meta_resolution": "0",
    "show_default_meta_ext": "0",
    "show_default_meta_codec": "0",
    "show_default_meta_bitrate": "0",
    "show_default_meta_fps": "0",
    "show_default_meta_number_media": "1",
    "show_default_meta_number_views": "1",
    "default_meta_chip_variant": "flat",
    "pathParser.useML": "true",
    "pathParser.similarityThreshold": "0.75",
    "pathParser.folderWeight": "1.5",
    "pathParser.clusterThreshold": "0.88",
  }),
  actions: {
    updateMultiple(data) {
      this.$patch(data)
    },
    // Обновить одно свойство состояния
    updateState({key, value}) {
      if (key in this.$state) {
        this[key] = value
      } else {
        console.warn(`Key "${key}" does not exist in items store`)
      }
    },
  },
})

export default useSettingsStore
