import { integer, real, sqliteTable, text } from 'drizzle-orm/sqlite-core'

export const meta = sqliteTable('meta', {
  id: integer('id').primaryKey({autoIncrement: true}),
  type: text('type'),
  name: text('name'),
  nameSingular: text('nameSingular'),
  icon: text('icon'),
  hint: text('hint'),
  order: integer('order'),
  views: integer('views').default(0),
  oldId: text('oldId'),
  synonyms: integer('synonyms', {mode: 'boolean'}).default(false),
  hidden: integer('hidden', {mode: 'boolean'}).default(false),
  nested: integer('nested', {mode: 'boolean'}).default(false),
  marks: integer('marks', {mode: 'boolean'}).default(false),
  bookmark: integer('bookmark', {mode: 'boolean'}).default(false),
  parser: integer('parser', {mode: 'boolean'}).default(false),
  country: integer('country', {mode: 'boolean'}).default(false),
  career: integer('career', {mode: 'boolean'}).default(false),
  scraper: integer('scraper', {mode: 'boolean'}).default(false),
  rating: integer('rating', {mode: 'boolean'}).default(false),
  favorite: integer('favorite', {mode: 'boolean'}).default(true),
  chipVariant: text('chipVariant').default('flat'),
  chipLabel: integer('chipLabel', {mode: 'boolean'}).default(false),
  color: integer('color', {mode: 'boolean'}).default(false),
  imageAspectRatio: real('imageAspectRatio').default(1),
  isLink: integer('isLink', {mode: 'boolean'}).default(false),
  ratingIcon: text('ratingIcon').default('star'),
  ratingIconEmpty: text('ratingIconEmpty').default('star-outline'),
  ratingIconHalf: text('ratingIconHalf').default('star-half-full'),
  ratingMax: integer('ratingMax').default(5),
  ratingColor: text('ratingColor').default('#ffab00'),
  ratingHalf: integer('ratingHalf', {mode: 'boolean'}).default(false),
  sortBy: text('sortBy').default('createdAt'),
  sortDir: text('sortDir').default('asc'),
  createdAt: text('createdAt').notNull(),
  updatedAt: text('updatedAt').notNull(),
})
